/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Event {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'registrationLink' : string,
  'dateTime' : Time,
  'location' : string,
  'eventType' : EventType,
}
export type EventType = { 'bibleStudy' : null } |
  { 'conference' : null } |
  { 'community' : null } |
  { 'sundayService' : null } |
  { 'youth' : null };
export interface GivingFund {
  'goalAmount' : [] | [bigint],
  'description' : string,
  'fundName' : string,
}
export interface NewsletterSubscriber { 'signupDate' : Time, 'email' : string }
export interface PrayerRequest {
  'id' : bigint,
  'submittedDate' : Time,
  'name' : string,
  'email' : string,
  'prayerText' : string,
}
export interface Sermon {
  'id' : bigint,
  'title' : string,
  'date' : Time,
  'tags' : Array<string>,
  'description' : string,
  'youtubeId' : string,
  'speaker' : string,
  'seriesName' : string,
}
export interface Testimony {
  'id' : bigint,
  'storyText' : string,
  'name' : string,
  'approved' : boolean,
  'category' : TestimonyCategory,
}
export type TestimonyCategory = { 'growth' : null } |
  { 'healing' : null } |
  { 'restoration' : null } |
  { 'faith' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveTestimony' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEvent' : ActorMethod<[Event], undefined>,
  'createGivingFund' : ActorMethod<[GivingFund], undefined>,
  'createSermon' : ActorMethod<[Sermon], undefined>,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'deleteGivingFund' : ActorMethod<[string], undefined>,
  'deleteSermon' : ActorMethod<[bigint], undefined>,
  'getAllGivingFunds' : ActorMethod<[], Array<GivingFund>>,
  'getAllNewsletterSubscribers' : ActorMethod<[], Array<NewsletterSubscriber>>,
  'getAllPrayerRequests' : ActorMethod<[], Array<PrayerRequest>>,
  'getAllSermons' : ActorMethod<[], Array<Sermon>>,
  'getAllUpcomingEvents' : ActorMethod<[], Array<Event>>,
  'getApprovedTestimonies' : ActorMethod<[], Array<Testimony>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEventsByType' : ActorMethod<[EventType], Array<Event>>,
  'getSermonsBySeries' : ActorMethod<[string], Array<Sermon>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchSermonsByTag' : ActorMethod<[string], Array<Sermon>>,
  'submitPrayerRequest' : ActorMethod<[PrayerRequest], undefined>,
  'submitTestimony' : ActorMethod<[Testimony], undefined>,
  'subscribeNewsletter' : ActorMethod<[string], undefined>,
  'updateEvent' : ActorMethod<[bigint, Event], undefined>,
  'updateGivingFund' : ActorMethod<[GivingFund], undefined>,
  'updateSermon' : ActorMethod<[bigint, Sermon], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];