/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const EventType = IDL.Variant({
  'bibleStudy' : IDL.Null,
  'conference' : IDL.Null,
  'community' : IDL.Null,
  'sundayService' : IDL.Null,
  'youth' : IDL.Null,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'registrationLink' : IDL.Text,
  'dateTime' : Time,
  'location' : IDL.Text,
  'eventType' : EventType,
});
export const GivingFund = IDL.Record({
  'goalAmount' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'fundName' : IDL.Text,
});
export const Sermon = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : Time,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'youtubeId' : IDL.Text,
  'speaker' : IDL.Text,
  'seriesName' : IDL.Text,
});
export const NewsletterSubscriber = IDL.Record({
  'signupDate' : Time,
  'email' : IDL.Text,
});
export const PrayerRequest = IDL.Record({
  'id' : IDL.Nat,
  'submittedDate' : Time,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'prayerText' : IDL.Text,
});
export const TestimonyCategory = IDL.Variant({
  'growth' : IDL.Null,
  'healing' : IDL.Null,
  'restoration' : IDL.Null,
  'faith' : IDL.Null,
});
export const Testimony = IDL.Record({
  'id' : IDL.Nat,
  'storyText' : IDL.Text,
  'name' : IDL.Text,
  'approved' : IDL.Bool,
  'category' : TestimonyCategory,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveTestimony' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEvent' : IDL.Func([Event], [], []),
  'createGivingFund' : IDL.Func([GivingFund], [], []),
  'createSermon' : IDL.Func([Sermon], [], []),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'deleteGivingFund' : IDL.Func([IDL.Text], [], []),
  'deleteSermon' : IDL.Func([IDL.Nat], [], []),
  'getAllGivingFunds' : IDL.Func([], [IDL.Vec(GivingFund)], ['query']),
  'getAllNewsletterSubscribers' : IDL.Func(
      [],
      [IDL.Vec(NewsletterSubscriber)],
      ['query'],
    ),
  'getAllPrayerRequests' : IDL.Func([], [IDL.Vec(PrayerRequest)], ['query']),
  'getAllSermons' : IDL.Func([], [IDL.Vec(Sermon)], ['query']),
  'getAllUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getApprovedTestimonies' : IDL.Func([], [IDL.Vec(Testimony)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEventsByType' : IDL.Func([EventType], [IDL.Vec(Event)], ['query']),
  'getSermonsBySeries' : IDL.Func([IDL.Text], [IDL.Vec(Sermon)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchSermonsByTag' : IDL.Func([IDL.Text], [IDL.Vec(Sermon)], ['query']),
  'submitPrayerRequest' : IDL.Func([PrayerRequest], [], []),
  'submitTestimony' : IDL.Func([Testimony], [], []),
  'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
  'updateEvent' : IDL.Func([IDL.Nat, Event], [], []),
  'updateGivingFund' : IDL.Func([GivingFund], [], []),
  'updateSermon' : IDL.Func([IDL.Nat, Sermon], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const EventType = IDL.Variant({
    'bibleStudy' : IDL.Null,
    'conference' : IDL.Null,
    'community' : IDL.Null,
    'sundayService' : IDL.Null,
    'youth' : IDL.Null,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'registrationLink' : IDL.Text,
    'dateTime' : Time,
    'location' : IDL.Text,
    'eventType' : EventType,
  });
  const GivingFund = IDL.Record({
    'goalAmount' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'fundName' : IDL.Text,
  });
  const Sermon = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : Time,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'youtubeId' : IDL.Text,
    'speaker' : IDL.Text,
    'seriesName' : IDL.Text,
  });
  const NewsletterSubscriber = IDL.Record({
    'signupDate' : Time,
    'email' : IDL.Text,
  });
  const PrayerRequest = IDL.Record({
    'id' : IDL.Nat,
    'submittedDate' : Time,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'prayerText' : IDL.Text,
  });
  const TestimonyCategory = IDL.Variant({
    'growth' : IDL.Null,
    'healing' : IDL.Null,
    'restoration' : IDL.Null,
    'faith' : IDL.Null,
  });
  const Testimony = IDL.Record({
    'id' : IDL.Nat,
    'storyText' : IDL.Text,
    'name' : IDL.Text,
    'approved' : IDL.Bool,
    'category' : TestimonyCategory,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveTestimony' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEvent' : IDL.Func([Event], [], []),
    'createGivingFund' : IDL.Func([GivingFund], [], []),
    'createSermon' : IDL.Func([Sermon], [], []),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'deleteGivingFund' : IDL.Func([IDL.Text], [], []),
    'deleteSermon' : IDL.Func([IDL.Nat], [], []),
    'getAllGivingFunds' : IDL.Func([], [IDL.Vec(GivingFund)], ['query']),
    'getAllNewsletterSubscribers' : IDL.Func(
        [],
        [IDL.Vec(NewsletterSubscriber)],
        ['query'],
      ),
    'getAllPrayerRequests' : IDL.Func([], [IDL.Vec(PrayerRequest)], ['query']),
    'getAllSermons' : IDL.Func([], [IDL.Vec(Sermon)], ['query']),
    'getAllUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getApprovedTestimonies' : IDL.Func([], [IDL.Vec(Testimony)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEventsByType' : IDL.Func([EventType], [IDL.Vec(Event)], ['query']),
    'getSermonsBySeries' : IDL.Func([IDL.Text], [IDL.Vec(Sermon)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchSermonsByTag' : IDL.Func([IDL.Text], [IDL.Vec(Sermon)], ['query']),
    'submitPrayerRequest' : IDL.Func([PrayerRequest], [], []),
    'submitTestimony' : IDL.Func([Testimony], [], []),
    'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
    'updateEvent' : IDL.Func([IDL.Nat, Event], [], []),
    'updateGivingFund' : IDL.Func([GivingFund], [], []),
    'updateSermon' : IDL.Func([IDL.Nat, Sermon], [], []),
  });
};

export const init = ({ IDL }) => { return []; };