/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Sermon {
    id: bigint;
    title: string;
    date: Time;
    tags: Array<string>;
    description: string;
    youtubeId: string;
    speaker: string;
    seriesName: string;
}
export type Time = bigint;
export interface PrayerRequest {
    id: bigint;
    submittedDate: Time;
    name: string;
    email: string;
    prayerText: string;
}
export interface GivingFund {
    goalAmount?: bigint;
    description: string;
    fundName: string;
}
export interface Event {
    id: bigint;
    title: string;
    description: string;
    registrationLink: string;
    dateTime: Time;
    location: string;
    eventType: EventType;
}
export interface NewsletterSubscriber {
    signupDate: Time;
    email: string;
}
export interface UserProfile {
    name: string;
}
export interface Testimony {
    id: bigint;
    storyText: string;
    name: string;
    approved: boolean;
    category: TestimonyCategory;
}
export enum EventType {
    bibleStudy = "bibleStudy",
    conference = "conference",
    community = "community",
    sundayService = "sundayService",
    youth = "youth"
}
export enum TestimonyCategory {
    growth = "growth",
    healing = "healing",
    restoration = "restoration",
    faith = "faith"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveTestimony(id: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createEvent(event: Event): Promise<void>;
    createGivingFund(fund: GivingFund): Promise<void>;
    createSermon(sermon: Sermon): Promise<void>;
    deleteEvent(id: bigint): Promise<void>;
    deleteGivingFund(fundName: string): Promise<void>;
    deleteSermon(id: bigint): Promise<void>;
    getAllGivingFunds(): Promise<Array<GivingFund>>;
    getAllNewsletterSubscribers(): Promise<Array<NewsletterSubscriber>>;
    getAllPrayerRequests(): Promise<Array<PrayerRequest>>;
    getAllSermons(): Promise<Array<Sermon>>;
    getAllUpcomingEvents(): Promise<Array<Event>>;
    getApprovedTestimonies(): Promise<Array<Testimony>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEventsByType(eventType: EventType): Promise<Array<Event>>;
    getSermonsBySeries(seriesName: string): Promise<Array<Sermon>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchSermonsByTag(tag: string): Promise<Array<Sermon>>;
    submitPrayerRequest(request: PrayerRequest): Promise<void>;
    submitTestimony(testimony: Testimony): Promise<void>;
    subscribeNewsletter(email: string): Promise<void>;
    updateEvent(id: bigint, event: Event): Promise<void>;
    updateGivingFund(fund: GivingFund): Promise<void>;
    updateSermon(id: bigint, sermon: Sermon): Promise<void>;
}
import type { Event as _Event, EventType as _EventType, GivingFund as _GivingFund, Testimony as _Testimony, TestimonyCategory as _TestimonyCategory, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveTestimony(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveTestimony(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveTestimony(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createEvent(arg0: Event): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(to_candid_Event_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(to_candid_Event_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createGivingFund(arg0: GivingFund): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createGivingFund(to_candid_GivingFund_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGivingFund(to_candid_GivingFund_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createSermon(arg0: Sermon): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSermon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSermon(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteGivingFund(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGivingFund(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGivingFund(arg0);
            return result;
        }
    }
    async deleteSermon(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSermon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSermon(arg0);
            return result;
        }
    }
    async getAllGivingFunds(): Promise<Array<GivingFund>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGivingFunds();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGivingFunds();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNewsletterSubscribers(): Promise<Array<NewsletterSubscriber>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNewsletterSubscribers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNewsletterSubscribers();
            return result;
        }
    }
    async getAllPrayerRequests(): Promise<Array<PrayerRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPrayerRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPrayerRequests();
            return result;
        }
    }
    async getAllSermons(): Promise<Array<Sermon>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSermons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSermons();
            return result;
        }
    }
    async getAllUpcomingEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUpcomingEvents();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUpcomingEvents();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApprovedTestimonies(): Promise<Array<Testimony>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedTestimonies();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedTestimonies();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventsByType(arg0: EventType): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsByType(to_candid_EventType_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsByType(to_candid_EventType_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSermonsBySeries(arg0: string): Promise<Array<Sermon>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSermonsBySeries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSermonsBySeries(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchSermonsByTag(arg0: string): Promise<Array<Sermon>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchSermonsByTag(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchSermonsByTag(arg0);
            return result;
        }
    }
    async submitPrayerRequest(arg0: PrayerRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPrayerRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPrayerRequest(arg0);
            return result;
        }
    }
    async submitTestimony(arg0: Testimony): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTestimony(to_candid_Testimony_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTestimony(to_candid_Testimony_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async subscribeNewsletter(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribeNewsletter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribeNewsletter(arg0);
            return result;
        }
    }
    async updateEvent(arg0: bigint, arg1: Event): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, to_candid_Event_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, to_candid_Event_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateGivingFund(arg0: GivingFund): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGivingFund(to_candid_GivingFund_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGivingFund(to_candid_GivingFund_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSermon(arg0: bigint, arg1: Sermon): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSermon(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSermon(arg0, arg1);
            return result;
        }
    }
}
function from_candid_EventType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventType): EventType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Event_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_GivingFund_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GivingFund): GivingFund {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_TestimonyCategory_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestimonyCategory): TestimonyCategory {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Testimony_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Testimony): Testimony {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    goalAmount: [] | [bigint];
    description: string;
    fundName: string;
}): {
    goalAmount?: bigint;
    description: string;
    fundName: string;
} {
    return {
        goalAmount: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.goalAmount)),
        description: value.description,
        fundName: value.fundName
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    description: string;
    registrationLink: string;
    dateTime: _Time;
    location: string;
    eventType: _EventType;
}): {
    id: bigint;
    title: string;
    description: string;
    registrationLink: string;
    dateTime: Time;
    location: string;
    eventType: EventType;
} {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        registrationLink: value.registrationLink,
        dateTime: value.dateTime,
        location: value.location,
        eventType: from_candid_EventType_n16(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    storyText: string;
    name: string;
    approved: boolean;
    category: _TestimonyCategory;
}): {
    id: bigint;
    storyText: string;
    name: string;
    approved: boolean;
    category: TestimonyCategory;
} {
    return {
        id: value.id,
        storyText: value.storyText,
        name: value.name,
        approved: value.approved,
        category: from_candid_TestimonyCategory_n21(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bibleStudy: null;
} | {
    conference: null;
} | {
    community: null;
} | {
    sundayService: null;
} | {
    youth: null;
}): EventType {
    return "bibleStudy" in value ? EventType.bibleStudy : "conference" in value ? EventType.conference : "community" in value ? EventType.community : "sundayService" in value ? EventType.sundayService : "youth" in value ? EventType.youth : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    growth: null;
} | {
    healing: null;
} | {
    restoration: null;
} | {
    faith: null;
}): TestimonyCategory {
    return "growth" in value ? TestimonyCategory.growth : "healing" in value ? TestimonyCategory.healing : "restoration" in value ? TestimonyCategory.restoration : "faith" in value ? TestimonyCategory.faith : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Testimony>): Array<Testimony> {
    return value.map((x)=>from_candid_Testimony_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GivingFund>): Array<GivingFund> {
    return value.map((x)=>from_candid_GivingFund_n10(_uploadFile, _downloadFile, x));
}
function to_candid_EventType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): _EventType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Event_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Event): _Event {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_GivingFund_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GivingFund): _GivingFund {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_TestimonyCategory_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestimonyCategory): _TestimonyCategory {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_Testimony_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Testimony): _Testimony {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    storyText: string;
    name: string;
    approved: boolean;
    category: TestimonyCategory;
}): {
    id: bigint;
    storyText: string;
    name: string;
    approved: boolean;
    category: _TestimonyCategory;
} {
    return {
        id: value.id,
        storyText: value.storyText,
        name: value.name,
        approved: value.approved,
        category: to_candid_TestimonyCategory_n28(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    description: string;
    registrationLink: string;
    dateTime: Time;
    location: string;
    eventType: EventType;
}): {
    id: bigint;
    title: string;
    description: string;
    registrationLink: string;
    dateTime: _Time;
    location: string;
    eventType: _EventType;
} {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        registrationLink: value.registrationLink,
        dateTime: value.dateTime,
        location: value.location,
        eventType: to_candid_EventType_n5(_uploadFile, _downloadFile, value.eventType)
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    goalAmount?: bigint;
    description: string;
    fundName: string;
}): {
    goalAmount: [] | [bigint];
    description: string;
    fundName: string;
} {
    return {
        goalAmount: value.goalAmount ? candid_some(value.goalAmount) : candid_none(),
        description: value.description,
        fundName: value.fundName
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestimonyCategory): {
    growth: null;
} | {
    healing: null;
} | {
    restoration: null;
} | {
    faith: null;
} {
    return value == TestimonyCategory.growth ? {
        growth: null
    } : value == TestimonyCategory.healing ? {
        healing: null
    } : value == TestimonyCategory.restoration ? {
        restoration: null
    } : value == TestimonyCategory.faith ? {
        faith: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): {
    bibleStudy: null;
} | {
    conference: null;
} | {
    community: null;
} | {
    sundayService: null;
} | {
    youth: null;
} {
    return value == EventType.bibleStudy ? {
        bibleStudy: null
    } : value == EventType.conference ? {
        conference: null
    } : value == EventType.community ? {
        community: null
    } : value == EventType.sundayService ? {
        sundayService: null
    } : value == EventType.youth ? {
        youth: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
